:sparkles: #2 - Add validation.
open-formulieren/formio-renderer pull request #25
Opened 2023-04-07 15:17 UTC by svenvandescheur

Closes #2 

TODO: Stories.

2023-04-18 10:00 UTC, sergei-maertens requested changes
Main principles look fine, just a couple remarks and thoughts

2023-04-18 15:53 UTC, svenvandescheur commented on src/lib/renderer/renderer.stories.tsx
> +  expect(await canvas.findByText('De opgegeven waarde voldoet niet aan het formaat.'));
As discussed: `findByText` is a more effective approach (without empty expect).

2023-04-18 16:44 UTC, svenvandescheur commented
@sergei-maertens I've replaced the `getComponentByKey` function with the Formik utils version, and reverted that change as it broke the build (build doesn't complete after this change).

2023-04-18 19:20 UTC, sergei-maertens commented on src/lib/validation/validate.ts
> +    );
I see - and at that point it might actually be more beneficial to do something like `errors as any as string` just to make TS shut up

2023-04-20 08:33 UTC, sergei-maertens commented
Merging this and I'll create a new PR to sort out the package build with `tsc` instead of this microbundle stuff

2023-04-20 08:39 UTC, merged